[package]
name = "QF"
version = "0.0.0"

[addresses]
std = "0x1"
QF = "0x223ba4fccb28befe994b429b6e3b9876451597aa7f15ccc531a89bb68c4f3cd0"

[dev-addresses]
QF = "0xC0FFEE"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosToken = { local = "../../framework/aptos-token" }

#[dependencies.AptosFramework]
#git = 'https://github.com/aptos-labs/aptos-core.git'
#rev = 'main'
#subdir = 'aptos-move/framework/aptos-framework'